# Configurações do servidor
server.port=8080

# Nome da aplicação
spring.application.name=api-viagem

# Configuração de logging
logging.level.com.agenciaviagem=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
